"""empty message

Revision ID: e12e55dec14f
Revises: 40a0658e61bc
Create Date: 2023-03-06 18:49:05.870554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12e55dec14f'
down_revision = '40a0658e61bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('is_org',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('is_org',
               existing_type=sa.String(length=80),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
